version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./stubs/s3:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  
#  webapi:
#    image: ${DOCKER_REGISTRY-}disbursementsverifier
#    build: 
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:80"
#    depends_on:
#      - localstack